# Generated by Django 3.0.5 on 2020-04-19 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PARK', 'park'), ('MUSEUM', 'museum'), ('MONUMENT', 'monument'), ('WORSHIP', 'worship'), ('LAKE', 'lake'), ('LIBRARY', 'library'), ('AMUSEMENT', 'amusement'), ('HOTEL', 'hotel'), ('ZOO', 'zoo')], default='PARK', max_length=10)),
                ('placesList', models.CharField(max_length=40, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('distance', models.FloatField(max_length=3)),
                ('congestion', models.CharField(choices=[('low', 'LOW'), ('moderate', 'MODERATE'), ('high', 'HIGH'), ('very high', 'VERY HIGH'), ('closed', 'CLOSED')], default='LOW', max_length=10)),
            ],
            options={
                'verbose_name': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'States',
            },
        ),
        migrations.CreateModel(
            name='PublicPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=40, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('distance', models.FloatField(max_length=3)),
                ('rating', models.FloatField(max_length=3)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('congestion', models.CharField(choices=[('low', 'LOW'), ('moderate', 'MODERATE'), ('high', 'HIGH'), ('very high', 'VERY HIGH'), ('closed', 'CLOSED')], default='LOW', max_length=10)),
                ('categoryPlaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'PublicPlaces',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('stateCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state', verbose_name='States')),
            ],
            options={
                'verbose_name': 'City',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='cityCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city', verbose_name='City'),
        ),
    ]
