# Generated by Django 3.0.5 on 2020-04-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplaces',
            name='closedtime',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='publicplaces',
            name='coordinates1',
            field=models.FloatField(default=2.2, max_length=8),
        ),
        migrations.AddField(
            model_name='publicplaces',
            name='coordinates2',
            field=models.FloatField(default=2.2, max_length=8),
        ),
        migrations.AddField(
            model_name='publicplaces',
            name='description',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='publicplaces',
            name='opentime',
            field=models.TimeField(default='9:00'),
        ),
    ]
